# Generated by Django 5.2 on 2025-04-19 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_ngouser_options_alter_ngouser_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ngouser',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ngouser',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
