# Generated by Django 5.2 on 2025-04-19 17:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_ngouser_groups_alter_ngouser_user_permissions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='associated_ngo',
            field=models.ForeignKey(blank=True, help_text='The NGO this donor is associated with', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donors', to=settings.AUTH_USER_MODEL),
        ),
    ]
